apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-flask-5000-v2
spec:
  selector:
    matchLabels:
      app: flask-app-v2
  replicas: 3
  template:
    metadata:
      labels:
        app: flask-app-v2
    spec:
      containers:
      - name: flask-pod-v2
        image: "us.gcr.io/nomadic-vertex-284501/flask-tutorial:v3"
        env:
        - name: "PORT"
          value: "5000"