apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-flask-50001
spec:
  selector:
    matchLabels:
      app: flask-app
  replicas: 3
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-pod
        image: "us.gcr.io/nomadic-vertex-284501/flask-tutorial"
        env:
        - name: "PORT"
          value: "5000"