apiVersion: v1
kind: Pod
metadata:
    name: flask-pod
    labels:
        zone: prod
        version: v1
spec:
    containers:
        - name: flask-ctr
          image: us.gcr.io/silver-aurora-284421/flask-tutorial
          ports:
            - containerPort: 8080